### ISSUE TITLE
Question around idiomaticity and performance of SomethingInCommon implementation

### ISSUE THREAD

**Issue by halk** [graphaware/neo4j-reco#5]
Hi,

I've attended the meetup earlier this year. While reviewing it, I came across the implementation of SomethingInCommon.java (see https://github.com/graphaware/neo4j-reco/blob/master/src/main/java/com/graphaware/reco/neo4j/engine/SomethingInCommon.java#L51).

The implementation loads all relationships of the input node with the requested type, loads the other node, loads all its relationships with the same type, loads the other node of that and adds the latter node to the collection if it's not the input node.

These are all separate queries thus I can't see how this can be performant. This also sounds very abnormal to the Neo4j functionality. I suggest you could do that with a single (or few) queries with Cypher?

Correct me if I got it wrong.

**Comment by bachmanm** [comment]
Hi,

you're right with your interpretation of the logic of the traversal. However, it is not true that these are separate "queries". This is a graph traversal rather than a query and happens very very fast. This is due to the fact that Neo4j stores data as graphs, in memory and (to an extent) on disk. Logically, the traversal is equivalent to the following Cypher query:

```
MATCH (input)-[:REL_TYPE]->(thingInCommon)<-[:REL_TYPE]-(recommendation)
RETURN recommendation
```

Typically, the Java API will be faster than Cypher, but this may change in the future. Once Cypher is predictably faster than the Java API, it would make sense to do what you're suggesting. 

The other reason this is in Java is to allow building more complicated logic into the recommendation engine in a clean way, using inheritance and composition.

**Comment by halk** [comment]
Thanks for the explanation. I have not used the Java API and have been using libraries with other languages which just run Cypher. Did not know that the Java API is different.
